sudo: required
services:
- docker

python:
- '2.7'
- '3.6'

go:
- "1.12"

language: python
install:
- pip install -e .[develop]
script:
- pyflakes recastatlas

jobs:
  include:
    # - stage: examplerun
    #   name: "Local Run"
    #   language: python
    #   install:
    #   - pip install -e .[local]
    #   script:
    #   - sudo apt-get install -y imagemagick
    #   - recast catalogue ls
    #   - recast run examples/rome
    - stage: examplerun
      name: "Local Docker Run"
      language: python
      install:
      - pip install -e .
      script:
      - recast catalogue ls
      - recast run examples/rome --backend docker
    - stage: examplerun
      name: "Kubernetes Run"
      install:
      - GO111MODULE=on go get sigs.k8s.io/kind
      - kind create cluster
      language: go
      script:
      - echo hello world
    - stage: deploy
      name: "Kubernetes Run"
      name: "Real PyPI"
      install:
        - echo none
      script:
        - echo none
      deploy:
        on:
          tags: true
          branch: master    
        provider: pypi
        username:
          secure: "MU+TNQ5FeEWWUYHf9/7ARAS4iUQUSIuGG/qROOamc5/xXZxJjSBMN++hN4oJjdNXKOn99X3Q8Zkh+qralMm+O9lAyod264z2sP+OHn/lVE1dziMt8TdlQPr9VSPHH+oZVKZCGRgVdS38xbgrYjN1NGtrld0JBuqoRvGUVHlxkwm9YD2cDLr5cGn2mD6KFTsVWuHTH4FkdWBqOT672Px9pn4EAWiotW9aWX0/8zf+rVb2fpfUDeqIjmTuTJKAKalFUoxQhyr5st9cceqcd83E35uQDhnsdLDnusgHohRxIbF3qFlfr+vUmtJ20/ac2GDy3yk3K8GtFp/YuEfWwyEp2lXAlmPtSN6lekH5ekalPkAFwdfjJVnzNsMgla2JDJqy/FhBy0yXgwZBDnk8CEDoS0cJxgNPPJ1sGwtSOZWP+8e2qTFDXrfb5ESBCgYxFf6m9eL0O7u4SK1UkvelHbf4z7EHuqAvJMz5Ep1Z9RQQUqtn/UpRrCR9ehBoW0RiDUYc7bDbudPIbPuek/TZO4wMRX1y+2xfVld+/M5kgmBvZFi2LJOp7Y3xZMB9oujoyiBt5Qcen7DlfutmYfAzgFvIOQfO1U5A2GMwFwp8+yKH/T/1/94zcy4E4mEI+plBOpWFtazMh1RJJVcx8sESJ3Q/enyCHApzCLaliubj3/MvXss="
        password:
          secure: "jmL78lvzZKkDvGZ5n6acIpNJ4+BbGHKxwaEstswlf3ThFmZIk08NQb5jaaOqB/+U7yeIU7JzEXZwPA3TMnvZZAG7vg0qc+xN5bsGrjmgM2IoVa1jWriAOObMkU9gXecssof+eBrYuGG+///mi3gEQy1TqBJwp1DPFbPWDwN3RVm79A/HUIphpIpRc1hsr/X+u/7DHRRwX3gMnyrmMf2R+43+zKClEZDW5FYkcdSlE5+1xVYR9bFO7bI7mJGUZWvo6HVs7IgHMrFxs8xjt5X4GZKElZm2k0F0kq5g9wSkDXdu5a8pKKAQ7gxjOsOJiCj/V/sEEQmTydjf7r6n2xO+Q3plh7SqV8BNAkZPxAREB6t8YGlZgwZbMbldPHoy4Xnj+yravvBV5ITd62nULxAe3Iaq/CqiXrRt9mqyJb28Xx2qZCTJpD7nhfk5boorw0nDeV9tG8f9N4V/UBQm9K/fjfsCUqYzv/GCdIZZyK2DayZMvDUx8UwKzcuFPOd4orGlXOYXP5gNhnTqRSOxKxKG6XIsoF/7A7A48Z81vhDkj+T4GqGaOgPX2cQll2old83tOdlfM0A3zrQ1c4c6SKLDxSKolvgkGkGnD9RW5Klv4rhyo5fiYsbDoINIPil1jBbXcaBbmqZC91ejVebVm+45yR7wqpVBa1nLU2Winyx5/d8="
    - stage: deploy
      name: "Test PyPI"
      install: skip
      script: skip
      deploy:
        on:
          all_branches: true
        env:
          # Signal that setup.py should use use_scm_version with local_scheme
          TESTPYPI_UPLOAD: true
        provider: pypi
        server: https://test.pypi.org/legacy/
        distributions: "sdist"
        skip_existing: true
        username:
          secure: "MU+TNQ5FeEWWUYHf9/7ARAS4iUQUSIuGG/qROOamc5/xXZxJjSBMN++hN4oJjdNXKOn99X3Q8Zkh+qralMm+O9lAyod264z2sP+OHn/lVE1dziMt8TdlQPr9VSPHH+oZVKZCGRgVdS38xbgrYjN1NGtrld0JBuqoRvGUVHlxkwm9YD2cDLr5cGn2mD6KFTsVWuHTH4FkdWBqOT672Px9pn4EAWiotW9aWX0/8zf+rVb2fpfUDeqIjmTuTJKAKalFUoxQhyr5st9cceqcd83E35uQDhnsdLDnusgHohRxIbF3qFlfr+vUmtJ20/ac2GDy3yk3K8GtFp/YuEfWwyEp2lXAlmPtSN6lekH5ekalPkAFwdfjJVnzNsMgla2JDJqy/FhBy0yXgwZBDnk8CEDoS0cJxgNPPJ1sGwtSOZWP+8e2qTFDXrfb5ESBCgYxFf6m9eL0O7u4SK1UkvelHbf4z7EHuqAvJMz5Ep1Z9RQQUqtn/UpRrCR9ehBoW0RiDUYc7bDbudPIbPuek/TZO4wMRX1y+2xfVld+/M5kgmBvZFi2LJOp7Y3xZMB9oujoyiBt5Qcen7DlfutmYfAzgFvIOQfO1U5A2GMwFwp8+yKH/T/1/94zcy4E4mEI+plBOpWFtazMh1RJJVcx8sESJ3Q/enyCHApzCLaliubj3/MvXss="
        password:
          secure: "jmL78lvzZKkDvGZ5n6acIpNJ4+BbGHKxwaEstswlf3ThFmZIk08NQb5jaaOqB/+U7yeIU7JzEXZwPA3TMnvZZAG7vg0qc+xN5bsGrjmgM2IoVa1jWriAOObMkU9gXecssof+eBrYuGG+///mi3gEQy1TqBJwp1DPFbPWDwN3RVm79A/HUIphpIpRc1hsr/X+u/7DHRRwX3gMnyrmMf2R+43+zKClEZDW5FYkcdSlE5+1xVYR9bFO7bI7mJGUZWvo6HVs7IgHMrFxs8xjt5X4GZKElZm2k0F0kq5g9wSkDXdu5a8pKKAQ7gxjOsOJiCj/V/sEEQmTydjf7r6n2xO+Q3plh7SqV8BNAkZPxAREB6t8YGlZgwZbMbldPHoy4Xnj+yravvBV5ITd62nULxAe3Iaq/CqiXrRt9mqyJb28Xx2qZCTJpD7nhfk5boorw0nDeV9tG8f9N4V/UBQm9K/fjfsCUqYzv/GCdIZZyK2DayZMvDUx8UwKzcuFPOd4orGlXOYXP5gNhnTqRSOxKxKG6XIsoF/7A7A48Z81vhDkj+T4GqGaOgPX2cQll2old83tOdlfM0A3zrQ1c4c6SKLDxSKolvgkGkGnD9RW5Klv4rhyo5fiYsbDoINIPil1jBbXcaBbmqZC91ejVebVm+45yR7wqpVBa1nLU2Winyx5/d8="
    - stage: deploy
      name: "Docker"
      install:
      - docker build -t recast/recastatlas:$TRAVIS_BRANCH $PWD
      script:
      - echo none
      deploy:
        on:
          all_branches: true
        #   tags: true
        #   branch: master            
        provider: script
        script: ./deploy/deploy.sh
        env:
        - secure: "KjSUS3XNT1lET3XTAqtdIYhiZcDPuI1g2z1cobr4R+LCFOti4dJ2wObJ0PFYeXDDRjq2e7OwqcoG1LVaGAjk6dFFkz5NU35j+V7jz/UACf1B8Ug8uMdjfJ7E3EDfVj/c9UOKR0B9G4XNb09lIebqxbF1aQZ+Somcjol6mPRq7Bd8+AVXeb2ZveYXbcy30rfY68bXaqdYz/jUFBEq2+z2VcZZKoA8v4GMcWj0wnJNgOzcMF9vQw7k/uF+qD2boxy4a3jVJH/KtT8w1ahGuzww22AoSQzjixsRPW7KRV+3Fl455j+V6zuRo2kI3qpduiTVmhvRkqP5U8YB9hD+q8bUdeEaSmybNQ2z1RyYT1gPnTESyqB0kUF2vgoB/7Q+mFiG1S/mYsVFBRo7CQTgOb96uALsK/jk8n7P2WUnf4g67DPO+H1nNotIE1uweV22NIESfaUUEsqBjB+o9LbjYZfjZh8XpQPnH8h24FcltSAGmSa5P2WBosIX5rPlTcR63VCy0t8PQQC7BrYD5xhBqVSPhnBbVd0iVfEPquofCyClhonX+v38gspjLGpn0iK4ZsZCaemn6aBVMgidTAxyus+DeXbibawFD0dr7GMUW7CJnGjPjcvUxtLq6j6epipz0bn4SVPh0XaR8WYih5pCrjMoGvLxDThQ2mb6ZSMnhphEgsU="        - secure: "HPfyKBeX69IHizV/0AzlWH2gTLaYG8BEXqxYXTz4XYHsKrqtGnyyJ5hilWB8ytTR2cVN/nq1vEBR3xTELZg+tmeVb8LrGZPJi5uc61SKfjs4ia1oYfOJKDcDVTZSZhcpG25UiXpug1SR3HImZyLpibB+T6FWCt3wwcVSACarzWZFCWhdmN+uEuAH4ym29sAZudnruBmLjxXleMQjB3lrGkb5ESgxnob+81zI4k+d1jIMKyL/lykyYT7tUGvTPXqfG9wUE4SKClHlNKdTg15yEXOf8S11YJFDCVs7YK4aMw8A59FQwFG6e1SLtlrQ2LKzKBLBgKNVJxFnBHxlI93EjdS0aDVcimddS6EMC1Dy1JzheoVbNssLhEES3l+64CyUkYYBU6NwR5jtDpnn02ZhNJ4tTHErxsoqEcb+AC1Y4yeo7GP6ERiFtH3VZChHH+HryYbpr6GoXdNX1Algo+aObEOzjSb82sL3nCeQS172EGLi2u0nRdoJGn2NV3oONuxKvHeQVrvlBmy8vRu/k7ymNp99BFXHfyFqOORoZ0kP3gUY0UNfkPiFgJ5GUOTMkUp/r7tVxiMhJppQuWonAFs5U0awUlUOLMesOk7kT5e75RQB5nH5P2sA6jj8mOg7UY99VaSZ/9wnwyVWgKJkR9Iv0KdkV+6pQTlcFeFyWlfm1TQ="
        - secure: "BJ7zsx/S35n0oOR1temshvw9bV7SupGxfaeO4XI5zBq6Py9E53sduGUAy/FeJEld6NhztuIl8n963mIRjlZwEgqZfspJCu334wJVrNSAQ8SJH5bdMJSHcY15kjOv9VTOwnuZgfnugex/hvmWMbk6E8k0/cHdL8c53f3gQTFPdq4are0gnLj9Lf7/1VC6Y2AyqCL3/Uj5eF5JA95Vtk47ZtV0mPkCu2mUvM+ohMDWCQD4L3yxcFhrbxmxCfmiRz1yyaTOEfG+3jaHMO2+Ns/FbjuYqmBs012hCJZD+WU5i4IVOXVuTkNlbGRo98cPNvXRhwhKEGDDNQL3Rr87tDpYjKFqIPNe/nXc+9u9Og82KPhi6rhhV9Vy7xr4jEoNgEnPcehNF1OafZ6OzlKUnXgx7JIGyMflx988C/5Qi0gwf44eh5kibAdlZBNPEX2GkiW3xpJPOZo+9WzCQdYEGrYsl4g3g18Mg7cC1xBcrdBnS9ttV5DJI9A3LJhZvGXL6U3qJMHWVmYP6pTEByE3fYyR1J1VrFbhNEfCZcD7EQg9BBhWUwetA0W9+Dr+1BR0MfvH4IknbSnYdhY7jPGT2MgFFuuY1Iq7gvda8tLRDEWn9caATEYvCPsz26Osmi2ZzzbXe+Y7o1xHkk2lH8DcIKnlpSgMZ1dlItIZKAfsbQXOJ4E="
