sudo: required
services:
- docker

python:
- '2.7'
- '3.6'

go:
- "1.12"

language: python
install:
- pip install -e .[develop]
script:
- pyflakes recastatlas

jobs:
  include:
    # - stage: examplerun
    #   name: "Local Run"
    #   language: python
    #   install:
    #   - pip install -e .[local]
    #   script:
    #   - sudo apt-get install -y imagemagick
    #   - recast catalogue ls
    #   - recast run examples/rome
    - stage: examplerun
      name: "Local Docker Run"
      language: python
      install:
      - pip install -e .
      script:
      - recast catalogue ls
      - recast run examples/rome --backend docker
    - stage: examplerun
      name: "Kubernetes Run"
      install:
      - GO111MODULE=on go get sigs.k8s.io/kind
      - kind create cluster
      language: go
      script:
      - echo hello world
    - stage: deploy
      name: "Kubernetes Run"
      name: "Real PyPI"
      install:
        - echo none
      script:
        - echo none
      deploy:
        on:
          tags: true
          branch: master    
        provider: pypi
        username:
          secure: "MU+TNQ5FeEWWUYHf9/7ARAS4iUQUSIuGG/qROOamc5/xXZxJjSBMN++hN4oJjdNXKOn99X3Q8Zkh+qralMm+O9lAyod264z2sP+OHn/lVE1dziMt8TdlQPr9VSPHH+oZVKZCGRgVdS38xbgrYjN1NGtrld0JBuqoRvGUVHlxkwm9YD2cDLr5cGn2mD6KFTsVWuHTH4FkdWBqOT672Px9pn4EAWiotW9aWX0/8zf+rVb2fpfUDeqIjmTuTJKAKalFUoxQhyr5st9cceqcd83E35uQDhnsdLDnusgHohRxIbF3qFlfr+vUmtJ20/ac2GDy3yk3K8GtFp/YuEfWwyEp2lXAlmPtSN6lekH5ekalPkAFwdfjJVnzNsMgla2JDJqy/FhBy0yXgwZBDnk8CEDoS0cJxgNPPJ1sGwtSOZWP+8e2qTFDXrfb5ESBCgYxFf6m9eL0O7u4SK1UkvelHbf4z7EHuqAvJMz5Ep1Z9RQQUqtn/UpRrCR9ehBoW0RiDUYc7bDbudPIbPuek/TZO4wMRX1y+2xfVld+/M5kgmBvZFi2LJOp7Y3xZMB9oujoyiBt5Qcen7DlfutmYfAzgFvIOQfO1U5A2GMwFwp8+yKH/T/1/94zcy4E4mEI+plBOpWFtazMh1RJJVcx8sESJ3Q/enyCHApzCLaliubj3/MvXss="
        password:
          secure: "jmL78lvzZKkDvGZ5n6acIpNJ4+BbGHKxwaEstswlf3ThFmZIk08NQb5jaaOqB/+U7yeIU7JzEXZwPA3TMnvZZAG7vg0qc+xN5bsGrjmgM2IoVa1jWriAOObMkU9gXecssof+eBrYuGG+///mi3gEQy1TqBJwp1DPFbPWDwN3RVm79A/HUIphpIpRc1hsr/X+u/7DHRRwX3gMnyrmMf2R+43+zKClEZDW5FYkcdSlE5+1xVYR9bFO7bI7mJGUZWvo6HVs7IgHMrFxs8xjt5X4GZKElZm2k0F0kq5g9wSkDXdu5a8pKKAQ7gxjOsOJiCj/V/sEEQmTydjf7r6n2xO+Q3plh7SqV8BNAkZPxAREB6t8YGlZgwZbMbldPHoy4Xnj+yravvBV5ITd62nULxAe3Iaq/CqiXrRt9mqyJb28Xx2qZCTJpD7nhfk5boorw0nDeV9tG8f9N4V/UBQm9K/fjfsCUqYzv/GCdIZZyK2DayZMvDUx8UwKzcuFPOd4orGlXOYXP5gNhnTqRSOxKxKG6XIsoF/7A7A48Z81vhDkj+T4GqGaOgPX2cQll2old83tOdlfM0A3zrQ1c4c6SKLDxSKolvgkGkGnD9RW5Klv4rhyo5fiYsbDoINIPil1jBbXcaBbmqZC91ejVebVm+45yR7wqpVBa1nLU2Winyx5/d8="
    - stage: deploy
      name: "Test PyPI"
      install: skip
      script: skip
      deploy:
        on:
          all_branches: true
        env:
          # Signal that setup.py should use use_scm_version with local_scheme
          TESTPYPI_UPLOAD: true
        provider: pypi
        server: https://test.pypi.org/legacy/
        distributions: "sdist"
        skip_existing: true
        username:
          secure: "MU+TNQ5FeEWWUYHf9/7ARAS4iUQUSIuGG/qROOamc5/xXZxJjSBMN++hN4oJjdNXKOn99X3Q8Zkh+qralMm+O9lAyod264z2sP+OHn/lVE1dziMt8TdlQPr9VSPHH+oZVKZCGRgVdS38xbgrYjN1NGtrld0JBuqoRvGUVHlxkwm9YD2cDLr5cGn2mD6KFTsVWuHTH4FkdWBqOT672Px9pn4EAWiotW9aWX0/8zf+rVb2fpfUDeqIjmTuTJKAKalFUoxQhyr5st9cceqcd83E35uQDhnsdLDnusgHohRxIbF3qFlfr+vUmtJ20/ac2GDy3yk3K8GtFp/YuEfWwyEp2lXAlmPtSN6lekH5ekalPkAFwdfjJVnzNsMgla2JDJqy/FhBy0yXgwZBDnk8CEDoS0cJxgNPPJ1sGwtSOZWP+8e2qTFDXrfb5ESBCgYxFf6m9eL0O7u4SK1UkvelHbf4z7EHuqAvJMz5Ep1Z9RQQUqtn/UpRrCR9ehBoW0RiDUYc7bDbudPIbPuek/TZO4wMRX1y+2xfVld+/M5kgmBvZFi2LJOp7Y3xZMB9oujoyiBt5Qcen7DlfutmYfAzgFvIOQfO1U5A2GMwFwp8+yKH/T/1/94zcy4E4mEI+plBOpWFtazMh1RJJVcx8sESJ3Q/enyCHApzCLaliubj3/MvXss="
        password:
          secure: "jmL78lvzZKkDvGZ5n6acIpNJ4+BbGHKxwaEstswlf3ThFmZIk08NQb5jaaOqB/+U7yeIU7JzEXZwPA3TMnvZZAG7vg0qc+xN5bsGrjmgM2IoVa1jWriAOObMkU9gXecssof+eBrYuGG+///mi3gEQy1TqBJwp1DPFbPWDwN3RVm79A/HUIphpIpRc1hsr/X+u/7DHRRwX3gMnyrmMf2R+43+zKClEZDW5FYkcdSlE5+1xVYR9bFO7bI7mJGUZWvo6HVs7IgHMrFxs8xjt5X4GZKElZm2k0F0kq5g9wSkDXdu5a8pKKAQ7gxjOsOJiCj/V/sEEQmTydjf7r6n2xO+Q3plh7SqV8BNAkZPxAREB6t8YGlZgwZbMbldPHoy4Xnj+yravvBV5ITd62nULxAe3Iaq/CqiXrRt9mqyJb28Xx2qZCTJpD7nhfk5boorw0nDeV9tG8f9N4V/UBQm9K/fjfsCUqYzv/GCdIZZyK2DayZMvDUx8UwKzcuFPOd4orGlXOYXP5gNhnTqRSOxKxKG6XIsoF/7A7A48Z81vhDkj+T4GqGaOgPX2cQll2old83tOdlfM0A3zrQ1c4c6SKLDxSKolvgkGkGnD9RW5Klv4rhyo5fiYsbDoINIPil1jBbXcaBbmqZC91ejVebVm+45yR7wqpVBa1nLU2Winyx5/d8="
    - stage: deploy
      name: "Docker"
      install:
      - docker build -t recast/recastatlas:$TRAVIS_BRANCH $PWD
      script:
      - echo none
      deploy:
        on:
          all_branches: true
        #   tags: true
        #   branch: master            
        provider: script
        script: ./deploy/deploy.sh
      env:
      - secure: "KjSUS3XNT1lET3XTAqtdIYhiZcDPuI1g2z1cobr4R+LCFOti4dJ2wObJ0PFYeXDDRjq2e7OwqcoG1LVaGAjk6dFFkz5NU35j+V7jz/UACf1B8Ug8uMdjfJ7E3EDfVj/c9UOKR0B9G4XNb09lIebqxbF1aQZ+Somcjol6mPRq7Bd8+AVXeb2ZveYXbcy30rfY68bXaqdYz/jUFBEq2+z2VcZZKoA8v4GMcWj0wnJNgOzcMF9vQw7k/uF+qD2boxy4a3jVJH/KtT8w1ahGuzww22AoSQzjixsRPW7KRV+3Fl455j+V6zuRo2kI3qpduiTVmhvRkqP5U8YB9hD+q8bUdeEaSmybNQ2z1RyYT1gPnTESyqB0kUF2vgoB/7Q+mFiG1S/mYsVFBRo7CQTgOb96uALsK/jk8n7P2WUnf4g67DPO+H1nNotIE1uweV22NIESfaUUEsqBjB+o9LbjYZfjZh8XpQPnH8h24FcltSAGmSa5P2WBosIX5rPlTcR63VCy0t8PQQC7BrYD5xhBqVSPhnBbVd0iVfEPquofCyClhonX+v38gspjLGpn0iK4ZsZCaemn6aBVMgidTAxyus+DeXbibawFD0dr7GMUW7CJnGjPjcvUxtLq6j6epipz0bn4SVPh0XaR8WYih5pCrjMoGvLxDThQ2mb6ZSMnhphEgsU="
      - secure: "GLnkxqgYx1lQKrHGv27ClBZ3yNM9sE4eNLyX6UnWkbHHQEtRVi07lLxjaJNOwYnpAf6h+iW0hK2njgmegCfc+/QttGCJ9q8tcsUwgWP7+/57CJFQg38A9uzxJMREFvyXJZiPRS+b6FmzH6HfiFDBaU3jU0ipmYwkOeBD/ZIvb9I/vFTzBNbKTxCcMgg/6ajjZVQLhOLN8drYOLM5sNZ+jW9NSvry9Sso8uO825jF9Gux06n2YrVPDpRKfaBasg1o4NNj6C74NQBQmI7Q3rgA00SYbGh35BcOEHIQpaRxqyVvqlGZvaDnHEuF64hrEO/oGK+CwVfsBLZSqzW85Sk9Ulvz4PZ8gc4j9U90siv6lY3zrCQg1F7f/NCQ2xYyTykSJPyDC9D9SxluwmU8orcQ7nO4D7jgeGznCLdbBa6nsjd/L7zJbeDPe6rcYrkSA1clug/Hp5qLoVsYP8WfW8+9nGDHSC5UYUAsr1VWoO2WotwPAal4yyyjs3fXcjWect/Mlu/UtGQu4ALLn8lSUBoPu7JcyhZarsN+m0cMhaDOoW0vJTZeLzIixMEcWnDPmaXHSeX5EVOXMWIB00R6hx6eqhYzHmQLZCrGlt+cD1svfgQ/nXy9ScQAbjoORT8BbkdgoOj57SGHUbNgjbtTd+VIRbsv6L4jAZCQN1F0pdQspys="
