sudo: required
services:
- docker

python:
- '2.7'
- '3.6'

go:
- "1.12"

jobs:
  include:
    - stage: testing
      language: python
      install:
      - pip install -e .[develop]
      script:
      - pyflakes recastatlas
    - stage: examplerun
      install:
      - pip install -U --process-dependency-links -e .
      script:
      - recast catalogue ls
      - recast run examples/rome --backend docker
    - stage: examplerun
      install:
      language: go
      install:
      - GO111MODULE=on go get sigs.k8s.io/kind
      - kind create cluster
      script:
      - echo hello world