name: CI/CD

on:
  push:
    branches:    
    - improvements         # Push events on master branch
    # tags:        
    #   - v1             # Push events to v1 tag
    #   - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  deploy:
    runs-on: ubuntu-master
    steps:
    - name: Docker Build
      run: |
        docker build -t recast/recastatlas:testdeploy -f docker/Dockerfile
      
    
