name: CI/CD

on:
  push:
    branches:    
    - improvements         # Push events on master branch
    # tags:        
    #   - v1             # Push events to v1 tag
    #   - v1.*           # Push events to v1.0, v1.1, and v1.9 tags


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Push
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker build -t recast/recastatlas:testbuild -f docker/Dockerfile $PWD
    - name: Docker Push
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        docker push recast/recastatlas:testbuild        
